// <auto-generated />
using System;
using BanVeXeKhach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BanVeXeKhach.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    partial class PostgreSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BanVeXeKhach.Models.DanhSachDatVe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("Khachid")
                        .HasColumnType("integer");

                    b.Property<int?>("NhaXeid")
                        .HasColumnType("integer");

                    b.Property<int?>("Tinhid")
                        .HasColumnType("integer");

                    b.Property<int>("idKhach")
                        .HasColumnType("integer");

                    b.Property<int>("idNhaXe")
                        .HasColumnType("integer");

                    b.Property<int>("idTinh")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Khachid");

                    b.HasIndex("NhaXeid");

                    b.HasIndex("Tinhid");

                    b.ToTable("DanhSachDatVe");
                });

            modelBuilder.Entity("BanVeXeKhach.Models.DanhSachTinhXeDiQua", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("NhaXeid")
                        .HasColumnType("integer");

                    b.Property<int?>("Tinhid")
                        .HasColumnType("integer");

                    b.Property<int>("giaVe")
                        .HasColumnType("integer");

                    b.Property<int>("idNhaXe")
                        .HasColumnType("integer");

                    b.Property<int>("idTinh")
                        .HasColumnType("integer");

                    b.Property<int>("thuTu")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("NhaXeid");

                    b.HasIndex("Tinhid");

                    b.ToTable("DanhSachTinhXeDiQua");
                });

            modelBuilder.Entity("BanVeXeKhach.Models.Khach", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("hoTen")
                        .HasColumnType("text");

                    b.Property<string>("soDienThoai")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Khach");
                });

            modelBuilder.Entity("BanVeXeKhach.Models.NhaXe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("bienSo")
                        .HasColumnType("text");

                    b.Property<string>("soDienThoai")
                        .HasColumnType("text");

                    b.Property<int>("soGheNam")
                        .HasColumnType("integer");

                    b.Property<int>("soGheNgoi")
                        .HasColumnType("integer");

                    b.Property<int>("taiTrongMoiKhach")
                        .HasColumnType("integer");

                    b.Property<string>("tenNhaXe")
                        .HasColumnType("text");

                    b.Property<string>("thoiGianDi")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("NhaXe");
                });

            modelBuilder.Entity("BanVeXeKhach.Models.Tinh", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("tenTinh")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("id");

                    b.HasIndex("tenTinh")
                        .IsUnique();

                    b.ToTable("Tinh");
                });

            modelBuilder.Entity("BanVeXeKhach.Models.DanhSachDatVe", b =>
                {
                    b.HasOne("BanVeXeKhach.Models.Khach", "Khach")
                        .WithMany()
                        .HasForeignKey("Khachid");

                    b.HasOne("BanVeXeKhach.Models.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("NhaXeid");

                    b.HasOne("BanVeXeKhach.Models.Tinh", "Tinh")
                        .WithMany()
                        .HasForeignKey("Tinhid");

                    b.Navigation("Khach");

                    b.Navigation("NhaXe");

                    b.Navigation("Tinh");
                });

            modelBuilder.Entity("BanVeXeKhach.Models.DanhSachTinhXeDiQua", b =>
                {
                    b.HasOne("BanVeXeKhach.Models.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("NhaXeid");

                    b.HasOne("BanVeXeKhach.Models.Tinh", "Tinh")
                        .WithMany()
                        .HasForeignKey("Tinhid");

                    b.Navigation("NhaXe");

                    b.Navigation("Tinh");
                });
#pragma warning restore 612, 618
        }
    }
}
